/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifndef _EMBFRITR_
#define _EMBFRITR_

#include <ODObject.idl>

interface ODEmbeddedFramesIterator : ODObject
{
	void InitEmbeddedFramesIterator(in ODPart part);
	ODFrame First();
	ODFrame Next();
	ODBoolean IsNotComplete();
	void PartRemoved();
	ODBoolean IsValid();
	void CheckValid();
#ifdef __SOMIDL__
	implementation
	{
		majorversion=1;
		minorversion=0;
		dllname="odcore.dll";
	#ifdef __PRIVATE__
		functionprefix="EmbFrItr_";
		override: somUninit;
	#endif
		releaseorder:
			InitEmbeddedFramesIterator,
			First,
			Next,
			IsNotComplete,
			PartRemoved,
			IsValid,
			CheckValid;
	};
#endif
};

#endif
