/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifndef _STDEXTS_
#define _STDEXTS_

#ifndef _ODTYPESM_
#include "ODTypesM.idl"
#endif

#if defined(__SOMIDL__) && defined(EMIT_GLOBAL_CONSTANTS)
#pragma somemittypes on
#endif

const ODType kODShellPlugIn             = "OpenDoc:Extension:Shell:PlugIn";
const ODType kODSettingsExtension       = "OpenDoc:Extension:Info:Settings";
const ODType kODExtSemanticInterface	= "OpenDoc:Extension:SemanticInterface";
const ODType kODScriptExtension         = "OpenDoc:Extension:AttachedScript";

#if defined(__SOMIDL__) && defined(EMIT_GLOBAL_CONSTANTS)
#pragma somemittypes off
#endif

module OpenDoc_StandardExtensions
{
	const string OpenDoc_StandardExtensions_Version = "1.0.";
};

#endif 
