/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifndef _STDPROPS_
#define _STDPROPS_

#include <ODTypesB.idl>

#if defined(__SOMIDL__) && defined(EMIT_GLOBAL_CONSTANTS)
#pragma somemittypes on
#endif

const ODPropertyName kODPropPreODMetaData="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:";
const ODPropertyName kODPropPreAnnotation="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Annotation:";
const ODPropertyName kODPropName="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:Name";
const ODPropertyName kODPropComments="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:Comments";
const ODPropertyName kODPropCreateDate="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:CreationDate";
const ODPropertyName kODPropModDate="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:ModifiedDate";
const ODPropertyName kODPropModUser="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:ModifiedUser";
const ODPropertyName kODPropObjectType="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:ObjectType";
const ODPropertyName kODPropStorageUnitType= "+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:StorageUnitType";
const ODPropertyName kODPropContents="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Property:Contents";
const ODPropertyName kODPropIsStationery="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:IsStationery";
const ODPropertyName kODPropPreferredEditor="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:PreferredEditor";
const ODPropertyName kODPropPreferredKind="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:PreferredKind";
const ODPropertyName kODPropDisplayFrames="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Annotation:DisplayFrames";
const ODPropertyName kODPropCustomIcon="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:CustomIcon";
const ODPropertyName kODPropEmbeddedFrames= "+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Property:EmbeddedFrames";
const ODPropertyName kODPropEmbeddedFramesOld= "OpenDoc:Property:EmbeddedFrames";
const ODPropertyName kODPropContainingFrame="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:ContainingFrame";
const ODPropertyName kODPropGraphicsSystem="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:GraphicsSystem";
const ODPropertyName kODPropFrameShape="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:FrameShape";
const ODPropertyName kODPropInternalTransform="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:InternalTransform";
const ODPropertyName kODPropBiasTransform="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:BiasTransform";
const ODPropertyName kODPropPart="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:Part";
const ODPropertyName kODPropPartInfo="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:PartInfo";
const ODPropertyName kODPropViewType="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:ViewType";
const ODPropertyName kODPropPresentation="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:Presentation";
const ODPropertyName kODPropFrameGroup="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:FrameGroup";
const ODPropertyName kODPropSequenceNumber="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:SequenceNumber";
const ODPropertyName kODPropIsRoot="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:IsRoot";
const ODPropertyName kODPropIsSubframe="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:IsSubFrame";
const ODPropertyName kODPropIsOverlaid="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:IsOverlaid";
const ODPropertyName kODPropIsFrozen="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:IsFrozen";
const ODPropertyName kODPropDoesPropagateEvents="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:DoesPropagateEvents";
const ODPropertyName kODPropLinkStatus="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:LinkStatus";
const ODPropertyName kODPropWindowProperties="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:WindowProperties";
const ODPropertyName kODPropLink="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:Link";
const ODPropertyName kODPropLinkSource="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:LinkSource";
const ODPropertyName kODPropLinkSpec="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:LinkSpec";
const ODPropertyName kODPropEmbedAsLink="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:EmbedAsLink";
const ODPropertyName kODPropSourcePart="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:SourcePart";
const ODPropertyName kODPropEditionAlias="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:EditionAlias";
const ODPropertyName kODPropLinkSection="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:LinkSection";
const ODPropertyName kODPropLinkContentSU="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:LinkContentSU";
const ODPropertyName kODPropAutoUpdate="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:AutoUpdate";
const ODPropertyName kODPropUpdateID="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:UpdateID";
const ODPropertyName kODPropChangeLimit="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:ChangeLimit";
const ODPropertyName kODPropChangeTime="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:ChangeTime";
const ODPropertyName kODPropContentKindsUsed="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:ContentKindsUsed";
const ODPropertyName kODPropOriginalID="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:OriginalID";
const ODPropertyName kODPropOriginalDraft="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:OriginalDraft";
const ODPropertyName kODPropOriginalCloneKind="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:OriginalCloneKind";
const ODPropertyName kODPropReservedSectionIDs= "+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:ReservedSectionIDs";
const ODPropertyName kODPropWindow="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:Window";
const ODPropertyName kODPropWindowRect="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:WindowRect";
const ODPropertyName kODPropWindowTitle="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:WindowTitle";
const ODPropertyName kODPropWindowProcID="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:WindowProcID";
const ODPropertyName kODPropWindowIsVisible="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:WindowVisible";
const ODPropertyName kODPropWindowHasCloseBox="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:WindowHasCloseBox";
const ODPropertyName kODPropWindowHasZoomBox="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:WindowHasZoomBox";
const ODPropertyName kODPropWindowIsResizable="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:WindowIsResizable";
const ODPropertyName kODPropWindowIsRootWindow= "+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:WindowIsRootWindow";
const ODPropertyName kODPropWindowIsFloating="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:WindowIsFloating";
const ODPropertyName kODPropWindowRefCon="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:WindowRefCon";
const ODPropertyName kODPropRootFrame="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:RootFrame";
const ODPropertyName kODPropSourceFrame="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:SourceFrame";
const ODPropertyName kODPropShouldShowLinks="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:ShouldShowLinks";
const ODPropertyName kODPropWindowCreateFlags="+//ISO 9070/ANSI::113722::US::CI LABS::WIN32:Property:WindowCreateFlags";
const ODPropertyName kODPropWindowSwpFlags="+//ISO 9070/ANSI::113722::US::CI LABS::WIN32:Property:WindowSwpFlags";
const ODPropertyName kODPropRootPartSU="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Property:Draft:RootPartStorageUnit";
const ODPropertyName  kODPropDraftNumber="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:Draft:Number";
const ODPropertyName  kODPropDraftComment="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:Draft:Comment";
const ODPropertyName kODPropEditionID="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:Draft:EditionID";
const ODPropertyName kODPropSectionID="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:Draft:SectionID";
const ODPropertyName kODPropRootFrameList="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:RootFrameList";
const ODPropertyName kODPropDraftSavedDate="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Metadata:DraftSavedDate";
const ODPropertyName  kODPropProxyContents="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Property:ProxyContents";
const ODPropertyName  kODPropContentFrame="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Property:ContentFrame";
const ODPropertyName  kODPropSuggestedFrameShape= "+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Property:SuggestedFrameShape";
const ODPropertyName  kODPropCloneKindUsed="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Property:CloneKindUsed";
const ODPropertyName  kODPropAttachedScriptType= "+//ISO 9070/ANSI::113722::US::IBM::OpenDoc:Property:AttachedScript";
#ifdef _PLATFORM_WIN32_
const ODPropertyName kODPropLinkItem="OpenDoc:Property:LinkItem";                  
const ODPropertyName kODPropMonikerFull="OpenDoc:Property:FullMoniker";          
const ODPropertyName kODPropMonikerRelative="OpenDoc:Property:RelativeMoniker";  
const ODPropertyName kODDefPropBgndColor="OpenDoc:Property:Default:BgndColor";  
const ODPropertyName kODDefPropFgndColor="OpenDoc:Property:Default:FgndColor";
const ODPropertyName kODDefPropErrorCaption="OpenDoc:Property:Default:ErrorCaption";
const ODPropertyName kODDefPropFont="OpenDoc:Property:Default:Font";           
const ODPropertyName kODDefPropDesignMode="OpenDoc:Property:Default:DesignMode";     
#endif
const ODPropertyName  kODPropMouseDownOffset="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Property:MouseDownOffset";
const ODPropertyName  kODPropPageSetup="+//ISO 9070/ANSI::113722::US::CI LABS::OpenDoc:Property:PageSetup";

#if defined(__SOMIDL__) && defined(EMIT_GLOBAL_CONSTANTS)
#pragma somemittypes off
#endif


#endif
