/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifndef _VALUENS_
#define _VALUENS_

#include <NamSpac.idl>

interface ODValueIterator;
typedef somToken PlatformFile;

interface ODValueNameSpace : ODNameSpace
{
	void Register(in ODISOStr key,in ODByteArray value);
	ODBoolean GetEntry(in ODISOStr key,out ODByteArray value);
	ODValueIterator CreateIterator();
#ifdef __PRIVATE__
	void InitValueNameSpace(in ODNameSpaceManager mgr,in ODNameSpace parent,in ODULong numExpectedEntries,in ODISOStr name);
	void Write(in PlatformFile *file,in ODStorageUnitView view);
	void Read(in PlatformFile *file,in ODStorageUnitView view);
#endif
#ifdef __SOMIDL__
	implementation
	{
		majorversion=1;
		minorversion=0;
		dllname="odcore.dll";
	#ifdef __PRIVATE__
		functionprefix="ValueNS_";
		override:
			somUninit,
			Purge,
			WriteToFile,
			ReadFromFile,
			WriteToStorage,
			ReadFromStorage;
	#endif
		releaseorder:
			Register,
			GetEntry,
			CreateIterator,
			InitValueNameSpace,
			Write,
			Read;
	};
#endif
};

#endif
