/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifndef _TYPELIST_
#define _TYPELIST_
#include <ODObject.idl>

interface ODTypeListIterator;

#ifdef __PRIVATE__
typedef somToken TypeList;
#endif

interface ODTypeList : ODObject
{
	void AddLast(in ODType type);
	void Remove(in ODType type);
	ODBoolean Contains(in ODType type);
	ODULong Count();
	ODTypeListIterator CreateTypeListIterator();

#ifdef __PRIVATE__
	void InitTypeList(in ODTypeList typeList);
	TypeList *GetImplementation();
#endif

#ifdef __SOMIDL__
	implementation
	{
		majorversion=1; 
		minorversion=0;
		dllname="odstorag.dll";
#ifdef __PRIVATE__
		functionprefix=TypeList_;
		override: somInit,somUninit;
		TypeList fTypeList;
#endif
		releaseorder:
			AddLast,
			Remove,
			Contains,
			Count,
			CreateTypeListIterator,
			InitTypeList,
			GetImplementation;
	};
#endif
};

#endif
