/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifndef _LINK_
#define _LINK_

#include <LinkB.idl>

interface  ODLink;
interface       ODStorageUnit;
interface       ODLinkSource;

#ifdef __PRIVATE__
#if defined(_PLATFORM_MACINTOSH_) || defined(_PLATFORM_X11_)
typedef somToken AliasHandle;
typedef somToken SectionHandle;
typedef somToken EditionContainerSpec;
#endif
typedef somToken FSSpec;
#endif

interface ODLink : ODBaseLink
{
#ifdef __PRIVATE__
	void InitLink(in ODStorageUnit storageUnit);
	void InitLinkFromStorage(in ODStorageUnit storageUnit);
#ifdef _PLATFORM_MACINTOSH_
    ODHandle GetPlatformValue(in ODPlatformType platformType, in ODLinkKey key);
    ODHandle CloneToMemoryContainer(in ODLinkKey key);
	AliasHandle CreateLinkEdition(in EditionContainerSpec editionContainer,in FSSpec *documentSpec,in ODULong sectionID,in ODLinkKey key);
	AliasHandle GetLinkEdition(in ODLinkKey key);
	void DeleteLinkEdition(in ODLinkKey key);
	void UpdateLinkEdition(in ODLinkKey key);
	void WriteLinkEdition(in SectionHandle section,in FSSpec *documentSpec,in ODLinkKey key);
#endif
#ifdef _PLATFORM_WIN32_
	ODHandle CloneIntoMemoryContainer(in ODLinkKey key);
	void RefreshDataObject(in ODLinkKey key);
	void UseItemName( in char *pszItemName );
	char* GetItemName( );
	somToken GetDataObject( in ODLinkKey key );
#endif
	void SetLinkDirty();
#endif

#ifdef __SOMIDL__
	implementation
	{
		majorversion=1; minorversion=0;
		dllname="oddatax.dll";
#ifdef __PRIVATE__
		functionprefix = Link_;
		override:
			UpdateDependents,
			somUninit,
			Release,
			Externalize,
			ReleaseAll,
		#if defined(_PLATFORM_MACINTOSH_) || defined(_PLATFORM_WIN32_) || defined(_PLATFORM_X11_)
			ShowLinkDestinationInfo,
		#endif
			CloneInto;

#if defined(_PLATFORM_MACINTOSH_) || defined (_PLATFORM_OS2_) 
		SectionHandle   fSection;
#endif
#ifdef _PLATFORM_WIN32_
		char*           fpszItemName;   /* OLE item moniker name */
		somToken          fpDataObject;   /* OLE data object */
#endif
		ODBoolean               fDirty;
#endif
		releaseorder:
  #ifdef _PLATFORM_MACINTOSH_
			InitLink,
			InitLinkFromStorage,
			CreateLinkEdition,
			GetLinkEdition,
			DeleteLinkEdition,
			UpdateLinkEdition,
			GetPlatformValue,
			CloneToMemoryContainer,
			WriteLinkEdition,
			SetLinkDirty,
  #else
			InitLink,
			InitLinkFromStorage,
			GetPlatformValue,
			ReservedA,
		#ifdef _PLATFORM_X11_
			CloneToMemoryContainer,
		#else
			CloneIntoMemoryContainer,
		#endif
			RefreshDataObject,
			UseItemName,
			GetItemName,
			GetDataObject,
			SetLinkDirty;
  #endif
	};
#endif
};

#endif
