/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifndef _WINWCANV_
#define _WINWCANV_

#include <WinPCanv.idl>

#if defined(_PLATFORM_WIN32_) && !defined(_PLATFORM_X11_)
interface ODWin32WindowCanvas : ODWin32Canvas
{
#ifdef __SOMIDL__
	implementation
	{
		majorversion=1;
		minorversion=0;
		dllname="odimagng.dll";
#ifdef __PRIVATE__
		override:
			HasWindow,
			IsInitialized,
			GetPlatformCanvasType,
			InitPlatformCanvas,
			InitPlatformWindowCanvas,
			GetDC,
			ReleaseDC,
			GetWindow,
			SetMetafileExtent,
			GetMetafileExtent;
		functionprefix="WinWCanv_";
		HWND fHWND;
		HDC fHdc;
		ODULong fCachedDCRefCount;
		ODBoolean fInitialized;
#endif /* __PRIVATE__ */
	};
#endif /* __SOMIDL__ */
};
#endif /* _PLATFORM_WIN32 && !_PLATFORM_X11_ */

#endif /* _WINWCANV_*/
