/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifdef __PRIVATE__

#ifndef _CMDOC_
#define _CMDOC_

#include <Document.idl>

interface   CMDocument;
interface	CMDraft;
interface	ODBentoContainer;

#ifdef __PRIVATE__
typedef somToken CMValue;
typedef somToken VersionList;
typedef somToken DraftList;
typedef somToken ODMemoryHeapID;
#endif

interface CMDocument :  ODDocument 
{
#ifdef __PRIVATE__
	CMValue GetCMVersionList();	
	CMDraft	AcquireDraftGut(in VersionList* versionList,in ODDraftPermissions perms,in ODDraftID id,in CMDraft draft,in ODPositionCode posCode,in ODBoolean release);
	void InternalizeVersionList();
	void ExternalizeVersionList(in ODBoolean ignoreTopDraft);
	void Reopen();
	VersionList* GetVersionList();
	VersionList* TestAndGetVersionList();
	void ReleaseVersionList();
	ODMemoryHeapID	GetHeap();
#endif

#ifdef __SOMIDL__
	implementation
	{
		majorversion = 1; minorversion = 0;
		dllname="odbento.dll";
#ifdef __PRIVATE__
	  	functionprefix = CMDoc_;
		
		override:
			somUninit,
			Purge,
			Release,
			GetContainer,
			GetID,
			GetName,
			SetName,
			CollapseDrafts,
			AcquireDraft,
			Exists,
			AcquireBaseDraft,
			CreateDraft,
			SaveToAPrevDraft,
			SetBaseDraftFromForeignDraft,
			InitDocument,
			ReleaseDraft;
#endif
		releaseorder:
			GetCMVersionList,
			AcquireDraftGut,
			InternalizeVersionList,
			ExternalizeVersionList,
			Reopen,
			GetVersionList,
			TestAndGetVersionList,
			ReleaseVersionList,
			GetHeap;
		#ifdef __PRIVATE__
			ODBentoContainer fContainer;
			ODDocumentID fID;
			DraftList *fDrafts;
			DraftList *fReleasedDrafts;
			VersionList *fVersions;
			ODULong	fVersionListSemaphore;
			ODMemoryHeapID fHeap;
			ODDocumentName fName;
		#endif
  };
#endif
};
#endif

#endif
