/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifndef _PARTKIND_
#define _PARTKIND_

#include <somobj.idl>
typedef string ISOString;

interface ODPartKind;
interface ODPartHandlerInfoInt;
interface PartSet;

interface ODPartKind  : SOMObject
{
	void                   InitODPartKind(in ISOString partKindName);
	ODPartHandlerInfoInt   GetPreferredPart();
	void                   SetPreferredPart(in ODPartHandlerInfoInt part);
	string                 GetKey();
	boolean                Add(in ODPartHandlerInfoInt part);
	void                   Remove(in ODPartHandlerInfoInt part); 
	long                   Count();
	attribute ISOString    partKindName;

#ifdef __SOMIDL__
	implementation
	{
		dllname="odregsty.dll";
	#ifdef __PRIVATE__
		functionprefix = ODPartKind;

		override:
			somInit,
			somUninit,
			somDumpSelfInt;
			partKindName: noset,noget;
			PartSet                 parts;
			boolean                 initialized;
			ODPartHandlerInfoInt    preferredPart;
	#endif

		releaseorder:
			InitODPartKind,
			GetPreferredPart,
			SetPreferredPart,
			GetKey,
			Add,
			Remove,
			Count,
			_get_partKindName,
			_set_partKindName;
	};
#endif
};
#endif
