/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifndef _NOPART_
#define _NOPART_

#include <Part.idl>

#ifdef __PRIVATE__
interface ODSession;
interface ODFocusSet;
interface ODMenuBar;
interface M_NoPart;
typedef somToken NoPartFacetInfo;
typedef somToken NoPartFrameInfo;
#endif

interface NoPart : ODPart
{
#ifdef __PRIVATE__
	void Initialize();
	void CheckAndAddProperties(in ODStorageUnit storageUnit);
	ODBoolean HandleMouseUp(in ODEventData event,in ODFrame frame,in ODFacet facet);
	ODBoolean HandleMenuEvent(in ODFrame frame,in ODEventData event);
	ODBoolean ActivateFrame(in ODFrame frame);
	ODWindow  MakeWindow(in ODFrame frame);
	void ActivatingWindow(in ODFrame frame);
	void DeactivatingWindow(in ODFrame frame);
#endif

#ifdef __SOMIDL__
	implementation
	{
        majorversion=1;
        minorversion=0;
		dllname="odbindng.dll";
        releaseorder:
            Initialize,
            CheckAndAddProperties,
            HandleMouseUp,
            HandleMenuEvent,
            ActivateFrame,
            MakeWindow,
            ActivatingWindow,
            DeactivatingWindow;
#ifdef __PRIVATE__
		metaclass=M_NoPart;
        functionprefix=NoPart;
        override:
			somInit,
			somUninit,
			FulfillPromise,
			DropCompleted,
			DragEnter,
			DragWithin,
			DragLeave,
			Drop,
			RevealFrame,
			EmbeddedFrameSpec,
			CreateEmbeddedFramesIterator,
			DisplayFrameAdded,
			DisplayFrameRemoved,
			DisplayFrameConnected,
			DisplayFrameClosed,
			AttachSourceFrame,
			FrameShapeChanged,
			ViewTypeChanged,
			PresentationChanged,
			SequenceChanged,
			WritePartInfo,
			ReadPartInfo,
			Open,
			RequestEmbeddedFrame,
			RemoveEmbeddedFrame,
			RequestFrameShape,
			UsedShapeChanged,
			AdjustBorderShape,
			FacetAdded,
			FacetRemoved,
			CanvasChanged,
			GeometryChanged,
			Draw,
			CanvasUpdated,
			HighlightChanged,
			GetPrintResolution,
			CreateLink,
			LinkUpdated,
			RevealLink,
			LinkStatusChanged,
			BeginRelinquishFocus,
			CommitRelinquishFocus,
			AbortRelinquishFocus,
			FocusAcquired,
			FocusLost,
			CloneInto,
			ExternalizeKinds,
			Externalize,
			ChangeKind,
			HandleEvent,
			AdjustMenus,
			UndoAction,
			RedoAction,
			DisposeActionState,
			WriteActionState,
			ReadActionState,
			InitPart,
			ClonePartInfo,
			InitPartFromStorage;

        ODSession       fSession;
        ODFocusSet      fFocusSet;
        ODTypeToken     fSelectionFocus;
        ODTypeToken     fMenuFocus;
        ODTypeToken     fKeyFocus;
        ODTypeToken     fModalFocus;
        ODTypeToken     fFrameView;
        ODTypeToken     fLargeIconView;
        ODTypeToken     fSmallIconView;
        ODTypeToken     fThumbnailView;
        ODTypeToken     fMainPresentation;
        ODStorageUnit   fPartSU;
        ODMenuBar       fMenuBar;
        ODID            fWindowID;
        ODPart          fPartWrapper;
		NoPartFrameInfo *fFirstItem;
		NoPartFrameInfo *fLastItem;
#endif
	};
#endif
};

#ifdef __PRIVATE__
interface M_NoPart : M_ODPart
{
#ifdef __SOMIDL__
	implementation
	{
		majorversion=1;
		minorversion=0;
		dllname="odbindng.dll";
		override:
			clsGetODPartHandlerName,
			clsGetODPartHandlerDisplayName,
			clsGetODPartKinds
#ifdef _PLATFORM_WIN32_
			,clsGetOLE2ClassId
			,clsGetWindowsIconFileName
#endif
			;
		functionprefix=M_NoPart;
	};
#endif
};
#endif

#endif

